# Generated by Django 6.0.7 on 2026-09-07 17:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchemaConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schema_id", models.CharField(max_length=128)),
                ("version", models.CharField(max_length=32)),
                ("definition", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schema_id", "version"),
                        name="unique_schema_config_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LayoutConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("layout", models.CharField(max_length=128)),
                ("document_type", models.CharField(max_length=64)),
                ("confidence_threshold", models.FloatField(default=0.75)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "schema_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="layout_configs",
                        to="catalog.schemaconfig",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("layout", "document_type"), name="unique_layout_config"
                    )
                ],
            },
        ),
    ]
