# Generated by Django 5.0.1 on 2026-05-03 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_integrationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digital_pdf_engine', models.CharField(choices=[('docling', 'Docling'), ('openrouter', 'OpenRouter'), ('tesseract', 'Tesseract')], default='docling', max_length=32)),
                ('scanned_image_engine', models.CharField(choices=[('docling', 'Docling'), ('openrouter', 'OpenRouter'), ('tesseract', 'Tesseract')], default='openrouter', max_length=32)),
                ('handwritten_engine', models.CharField(choices=[('docling', 'Docling'), ('openrouter', 'OpenRouter'), ('tesseract', 'Tesseract')], default='openrouter', max_length=32)),
                ('technical_fallback_engine', models.CharField(choices=[('docling', 'Docling'), ('openrouter', 'OpenRouter'), ('tesseract', 'Tesseract')], default='tesseract', max_length=32)),
                ('openrouter_model', models.CharField(blank=True, max_length=255)),
                ('openrouter_fallback_model', models.CharField(default='qwen/qwen2.5-vl-72b-instruct', max_length=255)),
                ('timeout_seconds', models.PositiveIntegerField(default=120)),
                ('retry_empty_text_enabled', models.BooleanField(default=True)),
                ('digital_pdf_min_text_blocks', models.PositiveIntegerField(default=5)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_settings', to='documents.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
