# Generated by Django 5.0.1 on 2026-05-03 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_ocrsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('imap', 'IMAP'), ('webhook', 'Webhook'), ('manual_test', 'Manual test')], default='imap', max_length=32)),
                ('inbox_folder', models.CharField(default='INBOX', max_length=255)),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('webhook_url', models.CharField(default='http://127.0.0.1:8070/api/v1/email/messages', max_length=1024)),
                ('accepted_content_types', models.CharField(default='application/pdf,image/jpeg,image/png,image/tiff,image/webp', max_length=1024)),
                ('max_attachment_mb', models.PositiveIntegerField(default=20)),
                ('blocked_senders', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='documents.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
