# Generated by Django 5.0.1 on 2026-06-22 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_userprofile_remove_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionFieldVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('INITIAL_EXTRACTION', 'Initial extraction'), ('PROCESSING', 'Processing'), ('REPROCESSING', 'Reprocessing'), ('MANUAL_EDIT', 'Manual edit')], max_length=32)),
                ('fields', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extraction_field_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_versions', to='documents.document')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='documents.extractionfieldversion')),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['document', 'version_number'], name='documents_e_documen_b80219_idx'), models.Index(fields=['document', 'is_active'], name='documents_e_documen_c41ec7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='extractionfieldversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_field_version_per_document'),
        ),
        migrations.AddConstraint(
            model_name='extractionfieldversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document',), name='unique_active_field_version_per_document'),
        ),
    ]
