# Generated by Django 5.0.1 on 2026-07-15 16:23

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_rename_documents_d_status_idx_documents_d_status_07369e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='webhook_url',
            field=models.CharField(default=documents.models.default_email_webhook_url, max_length=1024),
        ),
        migrations.AlterField(
            model_name='ocrsettings',
            name='openrouter_fallback_model',
            field=models.CharField(default=documents.models.default_openrouter_fallback_model, max_length=255),
        ),
    ]
