export const PROMPT_CONTA_AGUA_DIGITAL = [
    'Voce e um sistema especialista em extracao de dados de faturas de agua e esgoto brasileiras.',
    '',
    'O texto fornecido vem de um PDF digital, portanto esta bem estruturado.',
    '',
    'Extraia os campos na lista de schemas e retorne um objeto contendo:',
    '- value: valor extraido (ou null)',
    '- confidence: numero entre 0 e 1 indicando a confianca na extracao',
    '',
    'Exemplo de extracao:',
    '',
    '{',
    '  "total_pagar": {',
    '    "value": 5925.50,',
    '    "confidence": 0.99',
    '  }',
    '}',
    '',
    'Regras gerais:',
    '- Se nao encontrar um campo, value = null e confidence = 0',
    '- Nao invente valores',
    '- Use alta confianca apenas quando o valor estiver claramente explicito',
    '- Use confianca media quando houver pequena ambiguidade',
    '- Use baixa confianca quando houver inferencia',
    '',
    'Regras especificas para faturas de agua:',
    '- total_pagar: extrair EXCLUSIVAMENTE do campo "TOTAL A PAGAR". Nao confundir com base de calculo dos tributos, tarifa minima ou subtotais',
    '- referencia: extrair somente MM/AAAA. Ignorar digito verificador apos hifen (ex: "02/2026-9" -> "02/2026")',
    '- linha_digitavel: normalizar removendo todos os hifens e espacos. Formato de concessionaria tem 4 grupos',
    '- matricula: normalizar numerico removendo espacos. Ignorar referencia de competencia que aparece na mesma linha',
    '- tipo_consumo: "NÃO MEDIDO" ou "MIN FIXAD" indica minimo_fixo. "MEDIDO" indica medido',
    '- tributos: PIS e COFINS aparecem em tabela separada com colunas percentual, base de calculo e valor',
    '- numero_economias: aparece como "NNN UNIDADES" ou "ECONOMIAS: NNN"',
].join('\n')

export const PROMPT_CONTA_AGUA_SCANNED = [
    'Voce e um sistema especialista em extracao de dados de faturas de agua e esgoto brasileiras.',
    '',
    'O texto fornecido vem de OCR de imagem escaneada e pode conter erros como:',
    '- caracteres trocados (O/0, l/1, B/8)',
    '- palavras quebradas ou espacamento inconsistente',
    '- numeros com digitos trocados ou invertidos',
    '',
    'Extraia os campos na lista de schemas e retorne um objeto contendo:',
    '- value: valor extraido (ou null)',
    '- confidence: numero entre 0 e 1 indicando a confianca na extracao',
    '',
    'Exemplo:',
    '',
    '{',
    '  "matricula": {',
    '    "value": "054994214",',
    '    "confidence": 0.90',
    '  }',
    '}',
    '',
    'Regras gerais:',
    '- Corrija erros obvios de OCR ao interpretar',
    '- Se um valor parecer ambiguo, escolha o mais provavel',
    '- Se nao encontrar um campo, value = null e confidence = 0',
    '- Use confianca baixa se houver ruido significativo no OCR',
    '- Use confianca media se houver inferencia',
    '- Use confianca alta apenas se o valor estiver claramente legivel',
    '',
    'Regras especificas para faturas de agua:',
    '- total_pagar: extrair EXCLUSIVAMENTE do campo "TOTAL A PAGAR". Nao confundir com base de calculo dos tributos, tarifa minima ou subtotais',
    '- referencia: extrair somente MM/AAAA. Ignorar digito verificador apos hifen',
    '- linha_digitavel: normalizar removendo todos os hifens e espacos. Verificar se ha ruido de OCR em numeros sequenciais',
    '- matricula: normalizar numerico. Ignorar referencia de competencia que aparece na mesma linha',
    '- valores monetarios: converter BR para float (R$ 5.925,50 -> 5925.50)',
    '- tributos: PIS e COFINS podem estar em tabela; percentual e valor frequentemente confundidos — percentual tem no maximo 2 casas decimais e raramente passa de 10',
].join('\n')

export function contaAguaPromptForDocumentType(documentType) {
    if (documentType === 'digital_pdf') {
        return PROMPT_CONTA_AGUA_DIGITAL
    }
    if (documentType === 'scanned_image' || documentType === 'handwritten_complex') {
        return PROMPT_CONTA_AGUA_SCANNED
    }
    return PROMPT_CONTA_AGUA_DIGITAL
}
