@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Backend OCR

Container_Boundary(ocr, "Backend OCR") {

    Component(classifier, "Document Classifier", "Tipo de documento")
    Component(ocr_engine, "OCR Engine", "Extração de texto")
}

Container(queue, "Queue")
Container(layout, "Layout Classification Service")

Rel(queue, classifier, "job")
Rel(classifier, ocr_engine, "processar")
Rel(ocr_engine, layout, "raw_text")

@enduml