# Generated by Django 6.0.7 on 2026-08-22 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.UUIDField()),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('ERROR', 'Error')], max_length=16)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_type', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('orchestration_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='orchestrator.orchestrationrun')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
