# Generated by Django 6.0.7 on 2026-08-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationrun',
            name='document_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
