# Generated by Django 6.0.7 on 2026-08-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_orchestrationrun_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationrun',
            name='triggered_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
